package com.app.radiotime.utils

val countryList = listOf(
    Pair("🇦🇫 Afghanistan", "AF"),
    Pair("🇦🇱 Albania", "AL"),
    Pair("🇩🇿 Algeria", "DZ"),
    Pair("🇦🇸 American Samoa", "AS"),
    Pair("🇦🇩 Andorra", "AD"),
    Pair("🇦🇴 Angola", "AO"),
    Pair("🇦🇶 Antarctica", "AQ"),
    Pair("🇦🇬 Antigua And Barbuda", "AG"),
    Pair("🇦🇷 Argentina", "AR"),
    Pair("🇦🇲 Armenia", "AM"),
    Pair("🇦🇼 Aruba", "AW"),
    Pair("🇸🇭 Ascension And Tristan Da Cunha Saint Helena", "SH"),
    Pair("🇦🇺 Australia", "AU"),
    Pair("🇦🇹 Austria", "AT"),
    Pair("🇦🇿 Azerbaijan", "AZ"),
    Pair("🇧🇭 Bahrain", "BH"),
    Pair("🇧🇩 Bangladesh", "BD"),
    Pair("🇧🇧 Barbados", "BB"),
    Pair("🇧🇾 Belarus", "BY"),
    Pair("🇧🇪 Belgium", "BE"),
    Pair("🇧🇿 Belize", "BZ"),
    Pair("🇧🇯 Benin", "BJ"),
    Pair("🇧🇲 Bermuda", "BM"),
    Pair("🇧🇹 Bhutan", "BT"),
    Pair("🇻🇪 Bolivarian Republic Of Venezuela", "VE"),
    Pair("🇧🇴 Bolivia", "BO"),
    Pair("🇧🇶 Bonaire", "BQ"),
    Pair("🇧🇦 Bosnia And Herzegovina", "BA"),
    Pair("🇧🇼 Botswana", "BW"),
    Pair("🇧🇷 Brazil", "BR"),
    Pair("🇮🇴 British Indian Ocean Territory", "IO"),
    Pair("🇧🇳 Brunei Darussalam", "BN"),
    Pair("🇧🇬 Bulgaria", "BG"),
    Pair("🇧🇫 Burkina Faso", "BF"),
    Pair("🇧🇮 Burundi", "BI"),
    Pair("🇨🇻 Cabo Verde", "CV"),
    Pair("🇰🇭 Cambodia", "KH"),
    Pair("🇨🇲 Cameroon", "CM"),
    Pair("🇨🇦 Canada", "CA"),
    Pair("🇨🇱 Chile", "CL"),
    Pair("🇨🇳 China", "CN"),
    Pair("🇨🇴 Colombia", "CO"),
    Pair("🇨🇷 Costa Rica", "CR"),
    Pair("🇨🇮 Coted Ivoire", "CI"),
    Pair("🇭🇷 Croatia", "HR"),
    Pair("🇨🇺 Cuba", "CU"),
    Pair("🇨🇼 Curacao", "CW"),
    Pair("🇨🇾 Cyprus", "CY"),
    Pair("🇨🇿 Czechia", "CZ"),
    Pair("🇩🇰 Denmark", "DK"),
    Pair("🇩🇲 Dominica", "DM"),
    Pair("🇪🇨 Ecuador", "EC"),
    Pair("🇪🇬 Egypt", "EG"),
    Pair("🇸🇻 El Salvador", "SV"),
    Pair("🇬🇶 Equatorial Guinea", "GQ"),
    Pair("🇪🇪 Estonia", "EE"),
    Pair("🇸🇿 Eswatini", "SZ"),
    Pair("🇪🇹 Ethiopia", "ET"),
    Pair("🇫🇯 Fiji", "FJ"),
    Pair("🇫🇮 Finland", "FI"),
    Pair("🇫🇷 France", "FR"),
    Pair("🇬🇫 French Guiana", "GF"),
    Pair("🇵🇫 French Polynesia", "PF"),
    Pair("🇬🇪 Georgia", "GE"),
    Pair("🇩🇪 Germany", "DE"),
    Pair("🇬🇭 Ghana", "GH"),
    Pair("🇬🇮 Gibraltar", "GI"),
    Pair("🇬🇷 Greece", "GR"),
    Pair("🇬🇱 Greenland", "GL"),
    Pair("🇬🇩 Grenada", "GD"),
    Pair("🇬🇵 Guadeloupe", "GP"),
    Pair("🇬🇺 Guam", "GU"),
    Pair("🇬🇹 Guatemala", "GT"),
    Pair("🇬🇬 Guernsey", "GG"),
    Pair("🇬🇳 Guinea", "GN"),
    Pair("🇬🇾 Guyana", "GY"),
    Pair("🇭🇹 Haiti", "HT"),
    Pair("🇭🇳 Honduras", "HN"),
    Pair("🇭🇰 Hong Kong", "HK"),
    Pair("🇭🇺 Hungary", "HU"),
    Pair("🇮🇸 Iceland", "IS"),
    Pair("🇮🇳 India", "IN"),
    Pair("🇮🇩 Indonesia", "ID"),
    Pair("🇮🇶 Iraq", "IQ"),
    Pair("🇮🇪 Ireland", "IE"),
    Pair("🇮🇷 Islamic Republic Of Iran", "IR"),
    Pair("🇮🇲 Isle Of Man", "IM"),
    Pair("🇮🇱 Israel", "IL"),
    Pair("🇮🇹 Italy", "IT"),
    Pair("🇯🇲 Jamaica", "JM"),
    Pair("🇯🇵 Japan", "JP"),
    Pair("🇯🇪 Jersey", "JE"),
    Pair("🇯🇴 Jordan", "JO"),
    Pair("🇰🇿 Kazakhstan", "KZ"),
    Pair("🇰🇪 Kenya", "KE"),
    Pair("🇰🇮 Kiribati", "KI"),
    Pair("🇽🇰 Kosovo", "XK"),
    Pair("🇰🇼 Kuwait", "KW"),
    Pair("🇰🇬 Kyrgyzstan", "KG"),
    Pair("🇱🇻 Latvia", "LV"),
    Pair("🇱🇧 Lebanon", "LB"),
    Pair("🇱🇾 Libya", "LY"),
    Pair("🇱🇮 Liechtenstein", "LI"),
    Pair("🇱🇹 Lithuania", "LT"),
    Pair("🇱🇺 Luxembourg", "LU"),
    Pair("🇲🇴 Macao", "MO"),
    Pair("🇲🇬 Madagascar", "MG"),
    Pair("🇲🇼 Malawi", "MW"),
    Pair("🇲🇾 Malaysia", "MY"),
    Pair("🇲🇹 Malta", "MT"),
    Pair("🇲🇶 Martinique", "MQ"),
    Pair("🇲🇺 Mauritius", "MU"),
    Pair("🇾🇹 Mayotte", "YT"),
    Pair("🇲🇽 Mexico", "MX"),
    Pair("🇲🇨 Monaco", "MC"),
    Pair("🇲🇳 Mongolia", "MN"),
    Pair("🇲🇪 Montenegro", "ME"),
    Pair("🇲🇦 Morocco", "MA"),
    Pair("🇲🇿 Mozambique", "MZ"),
    Pair("🇲🇲 Myanmar", "MM"),
    Pair("🇳🇦 Namibia", "NA"),
    Pair("🇳🇵 Nepal", "NP"),
    Pair("🇳🇨 New Caledonia", "NC"),
    Pair("🇳🇿 New Zealand", "NZ"),
    Pair("🇳🇮 Nicaragua", "NI"),
    Pair("🇳🇬 Nigeria", "NG"),
    Pair("🇳🇫 Norfolk Island", "NF"),
    Pair("🇳🇴 Norway", "NO"),
    Pair("🇴🇲 Oman", "OM"),
    Pair("🇵🇰 Pakistan", "PK"),
    Pair("🇵🇦 Panama", "PA"),
    Pair("🇵🇾 Paraguay", "PY"),
    Pair("🇵🇪 Peru", "PE"),
    Pair("🇵🇱 Poland", "PL"),
    Pair("🇵🇹 Portugal", "PT"),
    Pair("🇵🇷 Puerto Rico", "PR"),
    Pair("🇶🇦 Qatar", "QA"),
    Pair("🇲🇰 Republic Of North Macedonia", "MK"),
    Pair("🇷🇪 Reunion", "RE"),
    Pair("🇷🇴 Romania", "RO"),
    Pair("🇷🇼 Rwanda", "RW"),
    Pair("🇰🇳 Saint Kitts And Nevis", "KN"),
    Pair("🇱🇨 Saint Lucia", "LC"),
    Pair("🇵🇲 Saint Pierre And Miquelon", "PM"),
    Pair("🇻🇨 Saint Vincent And The Grenadines", "VC"),
    Pair("🇸🇲 San Marino", "SM"),
    Pair("🇸🇹 Sao Tome And Principe", "ST"),
    Pair("🇸🇦 Saudi Arabia", "SA"),
    Pair("🇸🇳 Senegal", "SN"),
    Pair("🇷🇸 Serbia", "RS"),
    Pair("🇸🇨 Seychelles", "SC"),
    Pair("🇸🇱 Sierra Leone", "SL"),
    Pair("🇸🇬 Singapore", "SG"),
    Pair("🇸🇰 Slovakia", "SK"),
    Pair("🇸🇮 Slovenia", "SI"),
    Pair("🇸🇴 Somalia", "SO"),
    Pair("🇿🇦 South Africa", "ZA"),
    Pair("🇬🇸 South Georgia And The South Sandwich Islands", "GS"),
    Pair("🇪🇸 Spain", "ES"),
    Pair("🇱🇰 Sri Lanka", "LK"),
    Pair("🇵🇸 State Of Palestine", "PS"),
    Pair("🇸🇷 Suriname", "SR"),
    Pair("🇸🇪 Sweden", "SE"),
    Pair("🇨🇭 Switzerland", "CH"),
    Pair("🇸🇾 Syrian Arab Republic", "SY"),
    Pair("🇹🇼 Taiwan Province Of China", "TW"),
    Pair("🇹🇯 Tajikistan", "TJ"),
    Pair("🇹🇭 Thailand", "TH"),
    Pair("🇧🇸 The Bahamas", "BS"),
    Pair("🇰🇾 The Cayman Islands", "KY"),
    Pair("🇨🇫 The Central African Republic", "CF"),
    Pair("🇨🇨 The Cocos Keeling Islands", "CC"),
    Pair("🇰🇲 The Comoros", "KM"),
    Pair("🇨🇰 The Cook Islands", "CK"),
    Pair("🇰🇵 The Democratic Peoples Republic Of Korea", "KP"),
    Pair("🇨🇩 The Democratic Republic Of The Congo", "CD"),
    Pair("🇩🇴 The Dominican Republic", "DO"),
    Pair("🇫🇰 The Falkland Islands Malvinas", "FK"),
    Pair("🇫🇴 The Faroe Islands", "FO"),
    Pair("🇹🇫 The French Southern Territories", "TF"),
    Pair("🇻🇦 The Holy See", "VA"),
    Pair("🇳🇱 The Netherlands", "NL"),
    Pair("🇵🇭 The Philippines", "PH"),
    Pair("🇰🇷 The Republic Of Korea", "KR"),
    Pair("🇲🇩 The Republic Of Moldova", "MD"),
    Pair("🇷🇺 The Russian Federation", "RU"),
    Pair("🇸🇩 The Sudan", "SD"),
    Pair("🇹🇨 The Turks And Caicos Islands", "TC"),
    Pair("🇦🇪 The United Arab Emirates", "AE"),
    Pair("🇬🇧 The United Kingdom Of Great Britain And Northern Ireland", "GB"),
    Pair("🇺🇲 The United States Minor Outlying Islands", "UM"),
    Pair("🇺🇸 The United States Of America", "US"),
    Pair("🇹🇬 Togo", "TG"),
    Pair("🇹🇴 Tonga", "TO"),
    Pair("🇹🇹 Trinidad And Tobago", "TT"),
    Pair("🇹🇳 Tunisia", "TN"),
    Pair("🇹🇷 Turkey", "TR"),
    Pair("🇹🇲 Turkmenistan", "TM"),
    Pair("🇺🇬 Uganda", "UG"),
    Pair("🇺🇦 Ukraine", "UA"),
    Pair("🇹🇿 United Republic Of Tanzania", "TZ"),
    Pair("🇺🇾 Uruguay", "UY"),
    Pair("🇻🇮 US Virgin Islands", "VI"),
    Pair("🇺🇿 Uzbekistan", "UZ"),
    Pair("🇻🇺 Vanuatu", "VU"),
    Pair("🇻🇳 Vietnam", "VN"),
    Pair("🇼🇫 Wallis And Futuna", "WF"),
    Pair("🇾🇪 Yemen", "YE"),
    Pair("🇿🇲 Zambia", "ZM"),
    Pair("🇿🇼 Zimbabwe", "ZW")
)
